[package]
name = "music-library"
version = "0.1.0"
authors = ["daveystruijk <mail@daveystruijk.com>"]

[dependencies]
glob = "0.3.0"
id3 = "0.3.0"
clap = "2.33.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.22.3"
termimage = "0.5.0"
